image: Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python37"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python38"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"
build: off
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - "%PYTHON%\\python.exe -m pip install pycodestyle codecov"
  - "%PYTHON%\\python.exe -m pip install lxml"
  - "%PYTHON%\\python.exe setup.py install"
before_test:
  - "%PYTHON%\\Scripts\\pycodestyle.exe ."
test_script:
  - "%PYTHON%\\Scripts\\coverage.exe run --source=ebooks setup.py test"
after_test:
  - "%PYTHON%\\Scripts\\codecov.exe"
